=== elfer7/IPNCommunity/web/xml/dtd/escuela.DTD
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT escuela (informacion,carreras,estudiantes,profesores)>

<!ELEMENT informacion  (nombre,ubicacion,escudo,cover)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ubicacion (#PCDATA)>
<!ELEMENT escudo EMPTY >
<!ELEMENT cover EMPTY>

<!ELEMENT carreras  (carrera)*>
<!ELEMENT carrera (#PCDATA)>

<!ELEMENT estudiantes (usuario)*>
<!ELEMENT profesores (usuario)*>
<!ELEMENT usuario EMPTY>

<!ATTLIST escuela
id NMTOKEN #REQUIRED
tipo (superior|voacional) #REQUIRED>

<!ATTLIST escudo
url CDATA #REQUIRED>

<!ATTLIST cover
url CDATA #REQUIRED>

<!ATTLIST carrera
id NMTOKEN #REQUIRED>

<!ATTLIST usuario
id NMTOKEN #REQUIRED>

=== elfer7/IPNCommunity/web/escuelas/voca3/voca3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE escuela SYSTEM "C:\escuela.dtd" >-->
<escuela id="cecyt3" tipo="vocacional">
  <informacion>
    <nombre>"Estanislao Ramirez Ruiz"</nombre>
    <ubicacion>Av. Central, Valle de Ecatepec</ubicacion>
    <escudo url="escudo.jpg" />
    <cover url="cover.jpg" />
  </informacion>
  <carreras>
    <carrera id="AERO">Aeronautica</carrera>
    <carrera id="COMP">Computacion</carrera>
    <carrera id="MAC">Manufactura Asistida por Computadora</carrera>
    <carrera id="SA">Sistemas Automotrices</carrera>
    <carrera id="SCE">Sistemas de Control Electrico</carrera>
    <carrera id="SD">Sistemas Digitales</carrera>
  </carreras>
  <estudiantes />
  <profesores />
</escuela>
